### ISSUE TITLE
RangeError: Wrong length!

### ISSUE THREAD

**Issue by edemen** [nmaro/graphql-mongodb-example#14]
Hi

After cloning and doing yarn install and build, upon running yarn start I am getting this:

```
PS D:\work\repos\other\graphql-mongodb-example> yarn start
yarn run v1.17.3
$ node dist/index.js
RangeError: Wrong length!
    at validateArrayBufferArguments (D:\work\repos\other\graphql-mongodb-example\node_modules\core-js\modules\_typed-buffer.js:157:39)
    at new ArrayBuffer (D:\work\repos\other\graphql-mongodb-example\node_modules\core-js\modules\_typed-buffer.js:247:29)
    at zlib.js:334:28
    at NativeModule.compile (internal/bootstrap/loaders.js:300:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:217:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Function.Module._load (internal/modules/cjs/loader.js:685:15)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (D:\work\repos\other\graphql-mongodb-example\node_modules\body-parser\lib\read.js:18:12)
```

Could this be because of a dependency (or dependency of dependency) version?

**Comment by Fullchee** [comment]
I got the same error when I installed everything with yarn.

I deleted my `node_modules/.bin` folder and then ran

```npm i```

and then it worked

**Comment by edemen** [comment]
Great, thanks
