### ISSUE TITLE
Error connect to mongo in docker

### ISSUE THREAD

**Issue by rdeputat** [nmaro/graphql-mongodb-example#3]
$ yarn start
yarn run v1.3.2
$ node dist/index.js
{ MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/romandeputat/Projects/Test/GraphQL/graphql-mongo/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:160:13)
    at Connection.<anonymous> (/Users/romandeputat/Projects/Test/GraphQL/graphql-mongo/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:255:19)
    at Connection.emit (events.js:160:13)
    at Socket.<anonymous> (/Users/romandeputat/Projects/Test/GraphQL/graphql-mongo/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:255:19)
    at Socket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  name: 'MongoError',
  message: 'failed to connect to server [localhost:27017] on first connect' }
✨  Done in 1.97s.

https://hub.docker.com/_/mongo/

**Comment by MadhuriKankurte** [comment]
@nmaro  I have the issue
![image](https://user-images.githubusercontent.com/15665941/38596835-05591d48-3d7e-11e8-97d9-56ff5f0fc9a2.png)

**Comment by dopt** [comment]
I believe there's 2 ways you could face this problem
1. Anti-virus or firewall blocking the MongoDB
[](https://github.com/docker/hub-feedback/issues/1255)
2. MongoDB is not deployed yet on the localhost:27017, you can also choose to deploy it online instead to ease things up, follow the steps and you will get the new mongo_url to be replaced.
[](https://docs.mongodb.com/manual/installation/)
